name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: opened
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Nivel de detalle de ejecución'
        required: false
        default: 'info'
  schedule:
    - cron: '0 6 * * SUN'

jobs:
  selfhostedrunner:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: HolaMundo
        run: 'echo "Hola mundo desde un self-hosted runner"'
  CI:
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout
      uses: actions/checkout@v4  
    - name: Mostrar parámetros
      run: 'echo "Nivel seleccionado: ${{ inputs.logLevel }}"'
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
    - name: Instalar dependencias
      run: npm install
    - name: Ejecutar pruebas
      run: npm test
