name: CI-CD

on:
  push:
    branches: [main]
    paths: 'src/'
  pull_request:
    branches: [main]
    types: opened
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Nivel de detalle de ejecución'
        required: false
        default: 'info'
  schedule:
    - cron: '0 6 * * SUN'

env:
  AZURE_WEBAPP_NAME: gh200webapp3925
  AZURE_WEBAPP_PACKAGE_PATH: '.'   

jobs:
  selfhostedrunner:
    if: github.ref == 'refs/heads/developer'
    runs-on: self-hosted
    steps:
      - name: HolaMundo
        run: 'echo "Hola mundo desde un self-hosted runner"'
        
  CI:
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4  
    - name: Mostrar parámetros
      run: 'echo "Nivel seleccionado: ${{ inputs.logLevel }}"'
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
    - name: Instalar dependencias
      run: npm install
    - name: Ejecutar pruebas
      run: npm test
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache-

  CD:
   runs-on: ubuntu-latest
   needs: CI
   name: Deploy to Azure
   environment:
     name: Staging
   steps:
     - name: Download artifact from build job
       uses: actions/download-artifact@v4
       with:
         name: node-app

     - name: Ver contenido de la caché
       run: |
         ls -la ~/.npm
         
     - name: "Login via Azure CLI"
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
     - name: 'Deploy to Azure WebApp'
       id: deploy-to-webapp
       uses: azure/webapps-deploy@v2
       with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
     - name: Azure logout
       run: |
         az logout


     
   
